version: '3.9'

services:
  bob-works-front-end:
    container_name: bob-works-front-end
    image: ghcr.io/bob-park/bob-works-front-end-v2.1
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 3000:3000
