version: '3.9'

services:
  # bob-works-proxy:
  #   container_name: bob-works-proxy
  #   image: nginx:1.25.0
  #   network_mode: 'host'
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  bob-works-front-end:
    container_name: bob-works-front-end
    image: ghcr.io/bob-park/bob-works-front-end-v2.1
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 3000:3000
